### ISSUE TITLE
pod install outputs Unable to find a specification for `AccordionTableViewController`

### ISSUE THREAD

**Issue by ozzotto** [klevison/AccordionTableViewController#1]
My PodFile is the following.

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'
pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper.git', :branch => 'swift-2.0'
pod 'SlideMenuControllerSwift'
pod 'AccordionTableViewController'

When I pod install I get Unable to find a specification for `AccordionTableViewController`
I tried platform: '9.0' but still the same.
Maybe the use_frameworks flag?

**Comment by klevison** [comment]
I've removed from cocoapods.. I'll fix a little bug

On Sat, Aug 22, 2015 at 7:34 AM, Otto Antoniou notifications@github.com
wrote:

> My PodFile is the following.
> 
> source 'https://github.com/CocoaPods/Specs.git'
> platform :ios, '8.0'
> use_frameworks!
> 
> pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git',
> :branch => 'swift-2.0'
> pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper.git',
> :branch => 'swift-2.0'
> pod 'SlideMenuControllerSwift'
> pod 'AccordionTableViewController'
> 
> When I pod install I get Unable to find a specification for
> AccordionTableViewController
> I tried platform: '9.0' but still the same.
> Maybe the use_frameworks flag?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/klevison/AccordionTableViewController/issues/1.

## 

Klevison de Barros Matias
(82) 9313-1211 | klevison@gmail.com
http://www.linkedin.com/pub/klevison-matias/25/8aa/312

**Comment by klevison** [comment]
fixed
