### ISSUE TITLE
Xib Support

### ISSUE THREAD

**Issue by soniacasas** [klevison/AccordionTableViewController#4]
Hi! Amazing Work!

Is any option to use this framework with xibs? I'm not using SB.

Thanks a lot!

**Comment by klevison** [comment]
Sure, you can use XIB or SB. Have you got any problem?

**Comment by soniacasas** [comment]
Yes, I have a BaseViewController which all my views inherit, so I was thinking a way to don't use the TableViewController and just subclass the table view, is that possible?

Thanks

**Comment by klevison** [comment]
Yes, you can do it programmatically (`addChildViewController`).

1) Create a new class (subclassing from BaseViewController)
2) Create a AccordionTableViewController programmatically
3) Add AccordionTableViewController's view into the new class

http://stackoverflow.com/a/35888118/846780
